config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :teams
  resources :games do
    resources :notes, only: [ :index, :new, :create, :destroy ]
    resources :supporters, only: [ :new, :create, :destroy ]
    resources :comments, only: [ :new, :create ]
    member do
      get 'edit_score'
      get 'edit_quick'
      post 'edit_quick', to: 'games#update_quick'
      get 'widget'
      get 'widget/notes', to: 'notes#widget'
      post 'update_score'
    end
  end
  get '/games/:id/:timestamp/scoreboard', to: 'games#scoreboard', as: 'scoreboard_game'

  resources :users, only: [ :index, :show ]

  resources :sessions, only: [:create]
  get '/logout', to: 'sessions#clear'
  get '/auth/:provider/callback', to: 'sessions#create'

  get '/impressum', to: 'application#impressum'
  get '/datenschutz', to: 'application#datenschutz'
  get '/datenloeschung', to: 'application#datenloeschung'
  get '/nutzungsbedingungen', to: 'application#nutzungsbedingungen'

end

app/models/game.rb
class Game < ApplicationRecord

  PERIODS = %w(unstarted quarter_1 quarter_2 half quarter_3 quarter_4 final)

  belongs_to :user
  belongs_to :home_team, class_name: 'Team'
  belongs_to :away_team, class_name: 'Team'
  has_many :supporters
  has_many :notes
  has_many :comments

  validates :home_team, :away_team, presence: true

  scope :relevant, -> { where("game_day > '#{6.days.ago}' and game_day < '#{6.days.from_now}'") }
  scope :with_team, -> (team) { where("home_team_id = ? or away_team_id = ?", team, team) }

  def supported_by(user)
    Supporter.exists? user_id: user, game_id: self
  end

  def title
    "#{home_team.name} vs. #{away_team.name}"
  end

  def total_home
    total :home
  end

  def total_away
    total :away
  end

  def home_score(quarter)
    score :home, quarter
  end

  def away_score(quarter)
    score :away, quarter
  end

  def started?
    not unstarted?
  end

  def unstarted?
    period.to_sym == :unstarted
  end

  def playing?
    period.to_s.start_with? 'quarter'
  end

  def final?
    period.to_sym == :final
  end

  def total(type)
    (1..4).inject(0) do |sum, quarter|
      sum + score(type, quarter)
    end
  end

  def score(type, quarter)
    raise unless (1..4).include? quarter
    self.send("#{type}_quarter_#{quarter}")
  end

  def possession?(type)
    playing? && possession.try(:to_sym) == type.to_sym
  end

  # adds the amount of points to the home or away team in the current period if playing
  def add(team, points)
    raise 'not playing' unless playing?
    raise unless %w(home away).include? team
    current_points = send "#{team}_#{period}"
    send("#{team}_#{period}=", current_points + points.to_i)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_and_authorize_game, only: [:edit, :edit_score, :edit_quick, :update, :update_score, :update_quick, :destroy]
  before_action :set_game, only: [:show, :scoreboard, :notes, :widget]

  skip_before_action :force_https, only: :widget
  after_action :allow_iframe, only: :widget

  # GET /games
  # GET /games.json
  def index
    team_name = params[:team_name]
    team = Team.is_like(team_name).first if team_name.present?
    if team
      redirect_to team_path(team)
    end

    @show_jumbo = anonymous and request.path == '/'
    @games = Game.relevant.order(updated_at: :desc )
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @notes = @game.notes.recent 25
    @comments = @game.comments.recent 25
    if can? :create_supporter, @game
      @supporter = Supporter.new
    end
    if can? :create_comment, @game
      @comment = Comment.new
    end
  end

  def scoreboard
    respond_to do |format|
      format.html { render layout: 'plain' }
      format.jpg {
        img = generate_scoreboard_image
        send_data img, type: 'image/jpg', disposition: 'inline'
      }
    end
  end

  def widget
    @theme = widget_params[:theme] || :default
    render 'widget', layout: 'widget'
  end

  # GET /games/new
  def new
    @game = Game.new
    @game.game_day = Date.today
    @game.game_time = '15:00'
  end

  # GET /games/1/edit
  def edit
  end

  # GET /games/1/edit_score
  def edit_score
    @period_options = period_options
  end

  # GET /games/1/edit_score
  def edit_quick
    @period_options = period_options[1..-1]
    @notes = @game.notes.recent 25
  end

  def update_quick
    begin
      name = params[:name]
      value = params[:value]

      if name == 'period'
        raise unless Game::PERIODS.include? value
        @game.period = value
      elsif 'points' == name
        team = params[:team]
        @game.add(team, value)
      end

      @game.save

      render json: {message: "#{t("activerecord.values.game.period.#{@game.period}")}, #{@game.total_home} : #{@game.total_away}"}
    rescue Exception => e
      render json: {message: e.message}, status: 500
    end
  end

  # POST /games
  # POST /games.json
  def create
    p = game_params

    home_team_name = p.delete(:home_team_name)
    away_team_name = p.delete(:away_team_name)
    p[:home_team_id] = find_or_create_team(home_team_name).try(:id)
    p[:away_team_id] = find_or_create_team(away_team_name).try(:id)

    @game = Game.new(p)
    @game.user = current_user
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, notice: 'Game was successfully created.' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    p = game_params

    p[:home_team_id] = find_or_create_team(p.delete(:home_team_name)).try(:id) if p[:home_team_name].present?
    p[:away_team_id] = find_or_create_team(p.delete(:away_team_name)).try(:id) if p[:away_team_name].present?

    respond_to do |format|
      if @game.update(p)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  def set_and_authorize_game
    set_game
    authorize! action_name.to_sym, @game
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(
      :home_team_id, :home_team_name,
      :away_team_id, :away_team_name,
      :home_quarter_1, :home_quarter_2, :home_quarter_3, :home_quarter_4,
      :away_quarter_1, :away_quarter_2, :away_quarter_3, :away_quarter_4,
      :period, :possession,
      :location,
      :game_day, :game_time
    )
  end

  def widget_params
    params.permit(:theme)
  end

  def anonymous
    current_user.blank?
  end

  def find_or_create_team(team_name)
    Team.find_or_create_by(name: team_name) if team_name
  end

  def generate_scoreboard_image
    html =  render_to_string('scoreboard', layout: 'plain', formats: [:html])
    IMGKit.new(html, width: 360, height: 360).to_img
  end

  def period_options
    [].tap do |result|
      Game::PERIODS.each do |key|
        result << [ t("activerecord.values.game.period.#{key}"), key ]
      end      
    end
  end
end

app/helpers/game_helper.rb
module GameHelper

  def possession_marker(game, type)
    hidden_class = "hidden" unless game.possession? type
    content_tag :span, '',
      class: "possession-marker #{hidden_class} small glyphicon glyphicon-chevron-right",
      title: Game.human_attribute_name(:possession),
      data: { livescore_possession: type }
  end
end

app/views/games/_by_line.html.haml
.row.text-muted
  .col-xs-6
    = entity_image game.user, { version: :micro, size: 20, class: 'img-rounded' }
    %em= game.user.try :common_name
  .col-xs-6
    .score__updated.pull-right
      %span.glyphicon.glyphicon-time
      %em{data: {livescore_path: 'updated_at.words'}}= distance_of_time_in_words_to_now game.updated_at, include_seconds: true

app/views/games/_form.html.haml
= form_for @game do |f|
  .form-group{class: "#{'has-error' if @game.errors[:home_team].present?}"}
    = f.label :home_team_name
    %input{id: :home_team_name, name: 'game[home_team_name]', type: :text, value: @game.home_team.try(:name), placeholder: t('.team_name.placeholder.home'), autocomplete: :off, class: 'form-control js-typeahead', data: { url: "#{teams_path}", name: "teams", minlength: 2 }, 'aria-describedby' => 'hometeam_help'}
    %span#hometeam_help.help-block.small= t 'games.form.help.home_team'
  .form-group{class: "#{'has-error' if @game.errors[:away_team].present?}"}
    = f.label :away_team_name
    %input{id: :away_team_name, name: 'game[away_team_name]', type: :text, value: @game.away_team.try(:name), placeholder: t('.team_name.placeholder.away'), autocomplete: :off, class: 'form-control js-typeahead', data: { url: "#{teams_path}", name: "teams", minlength: 2 }, 'aria-describedby' => 'awayteam_help'}
    %span#awayteam_help.help-block.small= t 'games.form.help.away_team'
  .form-group
    = f.label :game_day
    .controls
      = f.date_field :game_day, :class => 'form-control', placeholder: "#{localize Date.today}"
  .form-group
    = f.label :game_time
    .controls
      = f.text_field :game_time, :class => 'form-control', placeholder: "15:00", maxlength: 255
  .form-group
    = f.label :location
    .controls
      = f.text_field :location, :class => 'form-control', maxlength: 255
  .form-group.form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), games_path, :class => 'btn btn-default'

app/views/games/_game.html.haml
.row
  .col-xs-12.scoreboard__period{data: {livescore_path: "period"} }= t("activerecord.values.game.period.#{game.period}")
.row
  - if game.final?
    .col-xs-12.scoreboard__game-day= localize game.game_day
  - else
    .col-xs-12.scoreboard__location= h game.location
.row.scoreboard__team_images
  .col-xs-3.scoreboard__team-image.home
    %a{href: team_path(game.home_team)}
      = entity_image game.home_team, version: :main
  .livescore__score.started_visible
    .col-xs-2.scoreboard__scores.home{data: {livescore_path: "score.home.total"} }= "#{game.total_home}"
    .col-xs-2.scoreboard__scores= "-"
    .col-xs-2.scoreboard__scores.away{data: {livescore_path: "score.away.total"} }= "#{game.total_away}"
  .livescore__date.started_hidden
    .col-xs-6.scoreboard__game-day
      %span.date= localize game.game_day
      - if game.game_time.present?
        %br
        %span.time= h game.game_time
  .col-xs-3.scoreboard__team-image.away
    %a{href: team_path(game.away_team)}
      = entity_image game.away_team, version: :main
-# Web
- [:home, :away].each do |type|
  .row.hidden-xs.scoreboard__team-score{class: type}
    .col-xs-8
      = possession_marker game, type
      = game.send("#{type}_team").name
    - (1..4).each do |quarter|
      .col-xs-1.scoreboard__period-score{data: {livescore_path: "score.#{type}.periods[#{quarter - 1}]"}}= game.score type, quarter

-# Mobile
- [:home, :away].each do |type|
  .row.visible-xs.scoreboard__team-score{class: type}
    .col-xs-4.scoreboard__team{class: type}
      = possession_marker game, type
      = game.send("#{type}_team").abbreviated_name
    - (1..4).each do |quarter|
      .col-xs-2.scoreboard__period-score{data: {livescore_path: "score.#{type}.periods[#{quarter - 1}]"}}= game.score type, quarter

app/views/games/_game_supporters.html.haml
.panel.panel-default
  .panel-heading= t('.title')
  - if game.supporters.blank?
    .panel-body
      %p= t('.none')
  - else
    %ul.list-group
    - game.supporters.each do |supporter|
      %li.list-group-item
        = entity_image supporter.user, { version: :micro, size: 20, class: 'img-rounded' }
        = supporter.user.common_name
        = link_to t('.links.destroy'), game_supporter_path(@game, supporter), :method => :delete, class: 'pull-right'
  .panel-body
    = form_for [game, @supporter], html: { class: 'form-inline', role: 'form' } do |f|
      .form-group
        = f.text_field :user, placeholder: t('.user_name.placeholder'), autocomplete: :off, class: 'form-control js-typeahead', data: { url: "#{users_path}", name: "users" }
      .form-actions
        = f.submit t('.links.create'), :class => 'btn btn-primary btn-xs'

app/views/games/_games.haml
- games.each_slice(2) do |row|
  .row
    - row.each do |game|
      .col-md-6.livescore{data: {url: "#{game_path game}"}, class: "#{'started' if game.started?} #{'js-livescore' unless game.final?}"}
        = render partial: '/games/by_line', locals: { game: game }
        .scoreboard__game
          =render partial: '/games/game', locals: { game: game }
          .row.scoreboard__actions
            - if can? :update_score, game
              .col-xs-6= link_to t('games.links.update_score'), edit_score_game_path(game), :class => 'btn btn-default btn-block'
            - if can? :update_score, game
              .col-xs-6= link_to t('games.links.update_quick'), edit_quick_game_path(game), :class => 'btn btn-primary btn-block'
            .col-xs-6= link_to t('games.links.show'), game_path(game), :class => 'btn btn-default btn-block'
            - if can? :create_note, game
              .col-xs-6= link_to t('games.links.create_note'), new_game_note_path(game), :class => 'btn btn-default btn-block'

app/views/games/_score_form.html.haml
= form_for @game, html: { class: 'form-horizontal scoreentry', role: 'form', autocomplete: :off } do |f|
  .row
    .col-xs-12
      %label= t('.possession')
  .row.form-group.scoreentry__possession
    .col-xs-4
      %label
        = f.radio_button :possession, nil
        = t('activerecord.game.possession.none')
    .col-xs-4
      %label
        = f.radio_button :possession, :home
        %span.hidden-xs= @game.home_team.name
        %span.visible-xs-inline= @game.home_team.abbreviated_name
    .col-xs-4
      %label
        = f.radio_button :possession, :away
        %span.hidden-xs= @game.away_team.name
        %span.visible-xs-inline= @game.away_team.abbreviated_name
  .row.scoreentry__team.home
    .col-xs-12
      %label= @game.home_team.name
  .row.form-group
    - (1..4).each do |quarter|
      .col-xs-3= f.text_field "home_quarter_#{quarter}", class: 'form-control', autocomplete: :off
  .row.scoreentry__team.away
    .col-xs-12
      %label= @game.away_team.name
  .row.form-group
    - (1..4).each do |quarter|
      .col-xs-3= f.text_field "away_quarter_#{quarter}", class: 'form-control', autocomplete: :off
  .row.scoreentry__period
    .col-xs-12
      %label= t('.period')
  .row.form-group
    .col-xs-12
      =f.select :period, @period_options, {}, {class: 'form-control'}
  .row
    .col-xs-12
      .scoreentry__actions.form-actions
        = f.submit nil, :class => 'btn btn-primary'
        = link_to t('.cancel', :default => t("helpers.links.cancel")), games_path, :class => 'btn'

app/views/games/edit.html.haml
- model_class = Game
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render "form"

app/views/games/edit_quick.html.haml
- content_for :js_footer do
  :javascript
    $('.js-quick-edit').quickupdate()

.page-header
  %h1=t '.title'
.js-quick-edit{data: {url: "#{edit_quick_game_path @game}"}}
  .row
    - @period_options.each_with_index do |period, index|
      - if index > 0 && index % 3 == 0
        %hr
      .col-xs-4
        %span.btn.btn-default.btn-block.js-quick-edit-value{data: {name: 'period', value: period[1]}}= period[0]
  - ['home', 'away'].each do |ha|
    %h2= @game.send("#{ha}_team").name
    .row
      .col-xs-3
        %span.btn.btn-default.btn-block.js-quick-edit-value{data: {name: "points", team: "#{ha}", value: 6}} TD 
      .col-xs-3
        %span.btn.btn-default.btn-block.js-quick-edit-value{data: {name: "points", team: "#{ha}", value: 1}} PAT
      .col-xs-3
        %span.btn.btn-default.btn-block.js-quick-edit-value{data: {name: "points", team: "#{ha}", value: 3}} FG
      .col-xs-3
        %span.btn.btn-default.btn-block.js-quick-edit-value{data: {name: "points", team: "#{ha}", value: 2}} 
          %span.hidden-xs Safety/2PC
          %span.visible-xs +2

%hr
.row
  .col-xs-12
    = link_to t('games.links.show'), game_path
    |
    = link_to t('games.links.update_score'), edit_score_game_path

%hr
=render 'notes/form', game: @game, note: Note.new, source: 'quick'

%hr
= render 'notes/game_notes', game: @game, notes: @notes

app/views/games/edit_score.html.haml
- model_class = Game
.page-header
  %h1=t '.title'
= render 'score_form'

app/views/games/index.html.haml
- content_for :js_footer do
  :javascript
    $('.js-livescore').livescore( {type: 'game', interval: 45 } )

- if @show_jumbo
  .jumbotron
    %h1=t '.jumbotron.title'
    %p=t '.jumbotron.description'
    %p.text-muted=t '.jumbotron.usage'
- else
  - content_for :title, t('.title')
- unless @current_user
  .row
    .col-sm-12
      .well.well
        .media
          .media-left.pull-left
            %a{href: '/auth/facebook'}
              = image_tag 'social/64/facebook.jpg', title: 'Facebook', class: 'img-rounded media-object'
          .media-body
            = t('.login_with_facebook')
            %a{href: '/auth/facebook'}= t '.login_now'
.page-header
  %h1=t '.title'
  %p.text-muted= t('games.info.reload_not_neccessary')

- if can? :create, Game
  .row
    .col-sm-12.spacer-bottom= link_to t(".links.new_game"), new_game_path, {class: 'btn btn-big btn-primary'}

.row.spacer-bottom
  .col-xs-12
    %h4= t '.team_name.headline'
    %form#team_search.form-inline{role: 'form', method: 'get', url: games_path }
      .form-group
        %input.form-control.input-sm.js-typeahead{name: 'team_name', type: 'text', placeholder: t('.team_name.placeholder'), autocomplete: :off, data: { url: "#{teams_path}", name: "teams" }}
      .form-group
        %input.btn.btn-default.input-sm{type: 'submit', value: t('.links.find_team')}
= render partial: 'games', locals: { games: @games }

app/views/games/new.html.haml
- model_class = Game
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
.container
  = render :partial => "form"

app/views/games/scoreboard.html.haml
.scoreboard
  - if @game.started?
    .score
      .team.home
        .logo= entity_image @game.home_team, version: :large, height: 90 + 40
        .score
          %span= @game.total_home
      .team.guest
        .logo= entity_image @game.away_team, version: :large, height: 90 + 40
        .score
          %span= @game.total_away
      .period
        %span= t("activerecord.values.game.period.#{@game.period}")
  - else
    .game-preview
      .teams
        .team.home
          .logo= entity_image @game.home_team, version: :large, height: 90 * 2
        .team.guest
          .logo= entity_image @game.away_team, version: :large, height: 90 * 2
      .info.date= localize @game.game_day
      - if @game.game_time.present?
        .info.time= h @game.game_time
      .info.location= @game.location

app/views/games/show.html.haml
- content_for :js_footer do
  :javascript
    $('.js-livescore').livescore({ type: 'game', interval: 35 })
    $('.js-livescore-notes').livescore({ type: 'notes' })

- title = @game.title
- content_for :title, h(title)

- content_for :meta_extra do
  %meta(property="og:image" content="#{scoreboard_game_url(@game, timestamp: @game.updated_at.to_i)}.jpg")
  %meta(property="og:updated_time" content="#{@game.updated_at.to_i}")
.page-header
  %h1= h title
  %p.text-muted= t('games.info.reload_not_neccessary')

.row.livescore{data: {url: "#{game_path @game}"}, class: "#{'started' if @game.started?} #{'js-livescore' unless @game.final?}"}
  .col-md-6
    = render partial: 'by_line', locals: { game: @game }
    .scoreboard__game
      = render partial: 'game', locals: { game: @game }

    .scoreboard__actions.row
      - if can? :update_score, @game
        .col-xs-6= link_to t('games.links.update_score'), edit_score_game_path(@game), :class => 'btn btn-default btn-block'
      - if can? :update_score, @game
        .col-xs-6= link_to t('games.links.update_quick'), edit_quick_game_path(@game), :class => 'btn btn-primary btn-block'
      - if can? :update, @game
        .col-xs-6= link_to t('games.links.update_game'), edit_game_path(@game), :class => 'btn btn-default btn-block'
      - if can? :create_note, @game
        .col-xs-6= link_to t('games.links.create_note'), new_game_note_path(@game), :class => 'btn btn-default btn-block'
      - if can? :destroy, @game
        .col-xs-6= link_to t('games.links.destroy'), game_path(@game), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-block'

  .col-md-6
    - if can? :update, @game
      .panel.panel-default
        .panel-heading
          = t('.share.title')
        .panel-body
          %p= t '.share.body'
          %textarea.form-control{rows: 3, readonly: true}= "<iframe src\"#{widget_game_url}\" width=\"100%\" height=\"250\" frameborder=\"0\"></iframe>"
    = render partial: 'notes/game_notes', locals: { game: @game, notes: @notes }

- if can? :create_supporter, @game
  - content_for :sidebar do
    = render partial: 'game_supporters', locals: { game: @game }

- content_for :sidebar do
  = render partial: 'comments/game_comments', locals: { game: @game, comments: @comments }

app/views/games/widget.html.haml
- content_for :js_footer do
  :javascript
    $('.js-livescore').livescore( {type: 'game', interval: 45 } )

.livescore{data: {url: "#{game_path @game}"}, class: "#{'started' if @game.started?} #{'js-livescore' unless @game.final?}"}
  .livescore__topbar
    %span.livescore__period{data: {livescore_path: "period"} }= t("activerecord.values.game.period.#{@game.period}")
    %span.livescore__location= truncate @game.location, length: 18
  .livescore__head
    .livescore__logos
      .livescore__logo_container
        .livescore__logo.home= entity_image @game.home_team, version: :large, size: 90
        .livescore__vs= 'vs.'
        .livescore__logo.away= entity_image @game.away_team, version: :large, size: 90
    .livescore__score.started_visible
      %span.home{data: {livescore_path: "score.home.total"} }= @game.total_home
      %span= "-"
      %span.away{data: {livescore_path: "score.away.total"} }= @game.total_away
    .livescore__date.started_hidden
      %span.date= localize @game.game_day
      - if @game.game_time.present?
        .livescore__time
          =@game.game_time

  .livescore__quarters.started_visible
    %table
      %thead
        %tr
          %th
          %th
          - (1..4).each do |quarter|
            %th= quarter
          %th= 'F'
      %tbody
        - [:home, :away].each do |type|
          %tr
            %td= @game.send("#{type}_team").name
            %td
            - (1..4).each do |quarter|
              %td.points{data: {livescore_path: "score.#{type}.periods[#{quarter - 1}]"}}= @game.score type, quarter
            %td.points{data: {livescore_path: "score.#{type}.total"} }= @game.total type
  .livescore__provided_by
    =link_to t('.provided_by'), game_url(@game), target: '_blank'