config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :teams
  resources :games do
    resources :notes, only: [ :index, :new, :create, :destroy ]
    resources :supporters, only: [ :new, :create, :destroy ]
    resources :comments, only: [ :new, :create ]
    member do
      get 'edit_score'
      get 'edit_quick'
      post 'edit_quick', to: 'games#update_quick'
      get 'widget'
      get 'widget/notes', to: 'notes#widget'
      post 'update_score'
    end
  end
  get '/games/:id/:timestamp/scoreboard', to: 'games#scoreboard', as: 'scoreboard_game'

  resources :users, only: [ :index, :show ]

  resources :sessions, only: [:create]
  get '/logout', to: 'sessions#clear'
  get '/auth/:provider/callback', to: 'sessions#create'

  get '/impressum', to: 'application#impressum'
  get '/datenschutz', to: 'application#datenschutz'
  get '/datenloeschung', to: 'application#datenloeschung'
  get '/nutzungsbedingungen', to: 'application#nutzungsbedingungen'

end

app/views/layouts/_footer.haml
%footer.text-center#footer
  .container
    .row
      .col-12.col-lg-6.col-lg-offset-3
        &copy; CodeKenner 2014&ndash;2021
        %br
        &copy;
        %a(href="https://tkn-consulting.de" target="_blank")
          tkn-consulting
        2021
      .col-12.col-lg-3
        %ul.pull-right.links
          %li
            %a(href='/impressum')
              Impressum
          %li
            %a(href='/datenschutz')
              Datenschutz
          %li
            %a(href='/datenloeschung')
              Datenlöschung
          %li
            %a(href='/nutzungsbedingungen')
              Nutzungsbedingungen

app/views/layouts/_google_analytics.html.haml
- unless ENV['ANALATICS_ACCOUNT'].blank? || Rails.env.development?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '#{ENV['ANALATICS_ACCOUNT']}', '#{request.host}');
    ga('send', 'pageview');
- else
  / analytics omitted intentionally

app/views/layouts/_navigation.html.haml
%header.navbar.navbar-default.navbar-static-top{role: 'banner'}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: '#livescore-navbar'}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      - if @current_user
        .navbar-avatar
          = entity_image @current_user, {size: 50, class: 'img-rounded' }
      %a.navbar-brand(href="/")
        Footballscores

    %nav.navbar-collapse.collapse{id: 'livescore-navbar'}
      %ul.nav.navbar-nav
        %li= link_to t("navbar.scoreboard"), games_path
        - if @current_user
          %li.dropdown
            %a.dropdown-toggle{href: '#', 'data-toggle' => "dropdown"}
              = "#{@current_user.common_name}"
              %span.caret
            %ul.dropdown-menu
              %li
                %a{href: "#{logout_path}"}
                  %span.glyphicon.glyphicon-log-out
                  = t('.logout')
        - else
          %li
            %a{href: '/auth/facebook'}
              = t('.login_with')
              = image_tag 'social/24/facebook.png', title: 'Facebook', class: 'img-rounded'

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'en', 'xmlns:og' => 'http://ogp.me/ns#' }
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    - if content_for? :meta_extra
      = yield(:meta_extra)

    - titles = ['Footballscores']
    - if content_for?(:title)
      - titles << yield(:title)
    %title=  titles.join(' | ')
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    = render 'layouts/navigation'
    .container
      .row
        .col-lg-9.livescore__main
          = bootstrap_flash
          = yield
        .col-lg-3
          - if content_for?(:sidebar)
            = yield :sidebar
          - else
            .well.sidebar-nav
              %h3
                = t('.sidebar.title')
                %br
                %small= t('.sidebar.sub_title')
              %ul.nav.nav-list
                - if @current_user
                  -# %li.nav-header= t('.sidebar.games')
                  - if can? :create, Game
                    %li= link_to t(".links.new_game"), new_game_path
                  - if can? :create, Team
                    %li= link_to t(".links.new_team"), new_team_path
              - unless @current_user
                %a{href: '/auth/facebook'}
                  %p= t(".sidebar.links.login_with_facebook")
                  = image_tag 'social/64/facebook.jpg', title: 'Facebook', class: 'img-rounded'


    = render partial: 'layouts/footer'

    = javascript_include_tag "application"
    - if content_for?(:js_footer)
      = yield :js_footer

    = render partial: 'layouts/google_analytics'

app/views/layouts/plain.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    = stylesheet_link_tag "application", :media => "all"

  %body.plain
    = yield

app/views/layouts/widget.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Livescore"
    = csrf_meta_tags
    = stylesheet_link_tag "widget", :media => "all"
    - if @theme.present?
      = stylesheet_link_tag "widget/theme_#{@theme}", :media => "all"
    = javascript_include_tag "livescore-lib"

  %body
    = yield

    - if content_for? :js_footer
      = yield :js_footer

    = render partial: 'layouts/google_analytics'